### ISSUE TITLE
Question: how to map GitHub usernames to Slack usernames?

### ISSUE THREAD

**Issue by rockstardev** [bryan-nice/slack-notification#9]
What I want is to take `GITHUB_ACTOR` variable and translate that GitHub username into optionally different Slack username so person can get mentioned in Slack about specific messages.

For example:

```
      - name: Slack Failure notification
        uses: bryan-nice/slack-notification@master
        if: failure()
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_ACTIONS_WEBHOOK }}
          SLACK_TITLE: 'GitHub Actions FAILURE'
          SLACK_MESSAGE: 'Build and Test failed to complete, cc: @SlackIdOfPersonThatTriggeredAction'
```

Is there an easy way to define this translation within the plug or I'll need to resort to some bash-fu magic?
